export const CONTENT = {
  splash: {
    title: "PALASMA 50 Tahun",
    subtitle: "Setengah Abad Alam, Petualangan, dan Persaudaraan",
    buttonLabel: "Buka Undangan",
    greeting: "Kepada Yth.",
    defaultName: "Abang / Mba",
  },
  hero: {
    welcome: "Selamat Datang",
    tagline: "Reuni Akbar\nPENCINTA ALAM SMAN 1 MATARAM",
    subtitle: "Setengah abad perjalanan, kenangan, dan persaudaraan yang tak pernah pudar.",
    ctaLabel: "Lihat Detail Acara",
    ctaTarget: "event-details",
  },
  rsvp: {
    ctaHadir: "Ya, Saya Hadir",
    ctaAbsen: "Maaf, Saya Absen",
  },
  sambutan: {
    title: "Kata Sambutan",
    body: "Assalamualaikum warahmatullahi wabarakatuh,\n\nPuji syukur ke hadirat Tuhan Yang Maha Esa, karena atas berkat dan rahmat-Nya kita dapat berkumpul kembali dalam acara Reuni Akbar HUT ke-50 PALASMA.\n\nSetengah abad sudah PALASMA berdiri, menemani perjalanan para pencinta alam dari berbagai angkatan. Melalui momen ini, kami mengajak seluruh keluarga besar PALASMA untuk bernostalgia, melepas rindu, dan merayakan pencapaian bersama.\n\nMari kita sambut hangat hari bahagia ini dengan penuh sukacita.\n\nWassalamualaikum warahmatullahi wabarakatuh,\n\nPanitia HUT ke-50 PALASMA",
    author: "Panitia",
    authorRole: "HUT ke-50 PALASMA",
  },
  modalApresiasi: {
    title: "Terima Kasih!",
    body: "Terima kasih sudah menjadi bagian dari perjalanan PALASMA selama ini. Meskipun tidak bisa hadir secara langsung, semangat dan kebersamaan kita tetap abadi. Kami sangat menghargai dukunganmu.\n\nSebagai bentuk partisipasi, kami mengajakmu untuk mengirimkan Video Ucapan atau Nostalgia berdurasi maksimal 1 menit. Video ini akan menjadi kenang-kenangan untuk seluruh keluarga besar PALASMA.\n\nPilih cara termudah untukmu:\n- Kirim langsung via WhatsApp\n- Upload ke Google Drive kami\n\nTerima kasih, PALASMA tetap di hati!",
    buttonWhatsApp: "Kirim via WhatsApp",
    buttonDrive: "Upload ke Google Drive",
    buttonTutup: "Tutup",
  },
  twibbon: {
    title: "Twibbon 50th PALASMA",
    subtitle: "Tunjukkan semangatmu sebagai bagian dari keluarga besar PALASMA",
    body: "Rancang Twibbon Anda sendiri dan bagikan ke media sosial untuk merayakan momen bersejarah HUT ke-50 PALASMA bersama-sama.",
    ctaLabel: "Pilih Foto",
    downloadLabel: "Download",
    zoomLabel: "Perbesar",
    rotateLabel: "Putar",
    resetLabel: "Ulangi",
    shareLabel: "Bagikan",
  },
  ucapan: {
    title: "Ucapan & Doa",
    subtitle: "Kirimkan ucapan dan doa terbaikmu untuk PALASMA",
    body: "Tulis pesanmu di sini — ucapan, doa, kenangan, atau harapan untuk masa depan PALASMA. Pesanmu akan menjadi bagian dari kenangan abadi setengah abad perjalanan kita bersama.",
    formName: "Nama Lengkap",
    formNamePlaceholder: "Masukkan nama",
    formBatch: "Angkatan",
    formBatchPlaceholder: "Contoh: 25",
    formOrganization: "Asal Organisasi / Komunitas",
    formOrganizationPlaceholder: "Contoh: Pencinta Alam NTB",
    formOrganizationHint: "Isi jika bukan anggota PALASMA",
    formBatchHint: "Isi jika anggota PALASMA",
    formMessage: "Pesan / Ucapan / Doa",
    formMessagePlaceholder: "Tulis ucapan, doa, atau kenangan terbaikmu untuk PALASMA...",
    submitLabel: "Kirim Ucapan",
    submittingLabel: "Mengirim...",
    successMessage: "Ucapan berhasil dikirim! Terima kasih atas partisipasimu.",
    errorMessage: "Terjadi kesalahan. Silakan coba lagi.",
    charCount: "{count}/500",
    emptyGallery: "Belum ada ucapan. Jadilah yang pertama mengirimkan doa dan ucapan!",
    noMoreMessages: "Tidak ada ucapan lain",
    supabaseUnconfigured: "Fitur ucapan belum tersedia. Silakan hubungi panitia.",
  },
  footer: {
    text: "© 2026 PALASMA",
    credit: "Dipersembahkan dengan penuh cinta oleh keluarga besar PALASMA",
  },
};
