import path from "node:path";
import Bun from "bun";

async function version() {
  const args = process.argv.slice(2);
  const commitRef = args[0] || "";

  const filepath = path.resolve("./src/utils/version-build.ts");
  const pkgPath = path.resolve("./package.json");
  const pkg = await Bun.file(pkgPath).json();
  const baseVersion = pkg.version || "0.0.0";

  let versionStr: string;

  if (commitRef && commitRef.length > 0) {
    const sha = commitRef.length > 7 ? commitRef.slice(0, 7) : commitRef;
    versionStr = `${baseVersion}-${sha}`;
  } else {
    versionStr = `${baseVersion}-local`;
  }

  const content = `// Generated by scripts/version.ts
export const buildVersion = "${versionStr}";`;

  await Bun.write(filepath, content);
  console.log(`Version generated: ${versionStr}`);
}

version();
